service/service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from clients.views import SendActivationEmailView

from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('accounts/', include('allauth.urls')),

    path('', include('services.urls', namespace='services')),
    path('clients/', include('clients.urls', namespace='clients')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('teach/', include('teach.urls', namespace='teach')),

    path('api/send_activation_email/', SendActivationEmailView.as_view(), name='send_activation_email_api'),

]+ debug_toolbar_urls()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

service/teach/urls.py
from django.urls import path
from rest_framework import routers

from teach.course_content_edit import TeachCourseModulesView, CreateModuleAPI, CreateLessonAPI
from teach.views import *

app_name = 'teach'


router = routers.SimpleRouter()
router.register('api/v1/course_edit_info', UpdateCourseView)
router.register('api/v1/course_edit_content_module', CreateModuleAPI)
router.register('api/v1/course_edit_content_lesson', CreateLessonAPI)



urlpatterns = [
    path('', TeachPromoView.as_view(), name='teach_promo'),
    path('courses/', TeachCoursesView.as_view(), name='courses'),
    path('courses/new/', TeachCourseCreate.as_view(), name='create_course'),
    path('courses/edit-info/<int:pk>/', TeachCourseInfoEditView.as_view(), name='course_edit_info'),
    path('courses/edit-content/<int:pk>/', TeachCourseModulesView.as_view(), name='course_edit_content'),
    # path('courses/edit-content/<int:pk>/', TeachCourseModulesView.as_view(), name='course_edit_content'),

    path('api/v1/teach-search/', TeachCoursesSearchView.as_view(), name='course_search'),
]+router.urls

service/services/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models, transaction
from django.urls import reverse_lazy
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel

from clients.models import Client
from services.tasks import set_sub_price


class Course(models.Model):
    LANG_CHOICES = (
        ('uk', 'Українська'),
        ('en', 'Англійська'),
    )
    DIFFICULTY_CHOICES = (
        ('beginner', 'Починаючий'),
        ('middle', 'Середній'),
        ('expert', 'Продвинутий'),
    )
    owner = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='courses')
    course_name = models.CharField(max_length=255)
    description = models.CharField(max_length=1024, blank=True, null=True)
    cat = models.ForeignKey('Category', on_delete=models.CASCADE, related_name='courses', null=True, blank=True)
    full_price = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0)])
    language = models.CharField(choices=LANG_CHOICES, max_length=255)
    difficulty = models.CharField(choices=DIFFICULTY_CHOICES, max_length=255, null=True)
    have_certificate = models.BooleanField(default=False)
    preview = models.ImageField(upload_to='course_previews/%Y/%m/%d/', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)

    def get_absolute_url(self):
        return reverse_lazy('services:course_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.course_name

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__full_price = self.full_price

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.full_price != self.__full_price:
            for sub in self.subscriptions.all():
                set_sub_price.delay(sub.id)

class CourseInfo(models.Model):
    course = models.OneToOneField(Course, on_delete=models.CASCADE, related_name='info')
    workload = models.IntegerField(default=0, validators=[MinValueValidator(0)], blank=True, null=True)
    authors = models.ManyToManyField(Client, related_name='authors', blank=True)
    preview_video = models.URLField(blank=True, null=True)



class CourseModules(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='modules')
    title = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    order = models.PositiveIntegerField(default=0)  # Порядок отображения

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f'Course: {self.course} - Cat: {self.title}'


class Lesson(models.Model):
    course_module = models.ForeignKey(CourseModules, on_delete=models.CASCADE, related_name='lessons')
    title = models.CharField(max_length=255)
    content = models.TextField(blank=True, null=True)  # Основной текст урока
    video_url = models.URLField(blank=True, null=True)  # URL для видео

    def __str__(self):
        return f' Lesson: {self.title}'


# class TextTest(models.Model):
#     lesson = models.ForeignKey('Lesson', on_delete=models.CASCADE, related_name='text_tests')
#     question = models.CharField(max_length=255)
#     answer = models.TextField()
#
#     def __str__(self):
#         return self.question


class Plan(models.Model):
    PLAN_TYPES = (
        ('full', 'Повний'),
        ('student', 'Студентський'),
        ('discount', 'Акційний')
    )
    plan_type = models.CharField(choices=PLAN_TYPES, max_length=20)
    discount_percent = models.IntegerField(default=0, validators=[MaxValueValidator(100)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.plan_type

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__discount_percent = self.discount_percent

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.discount_percent != self.__discount_percent:
            for sub in self.subscriptions.all():
                set_sub_price.delay(sub.id)


class Subscription(models.Model):
    course = models.ForeignKey(Course, on_delete=models.PROTECT, related_name='subscriptions')
    plan = models.ForeignKey(Plan, on_delete=models.PROTECT, related_name='subscriptions')
    client = models.ForeignKey(Client, on_delete=models.PROTECT, related_name='subscriptions')
    price = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0)])
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.client} - {self.plan} - {self.course}'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        creating = not self.pk
        if not creating:
            self.__plan = self.plan

    def save(self, *args, **kwargs):
        creating = not self.pk

        result = super().save(*args, **kwargs)

        if creating or self.plan != self.__plan:
            set_sub_price.delay(self.id)
        return result

    # def delete(self, **kwargs):
    #     cache.delete(settings.PRICE_CACHE_NAME)
    #     super().delete(**kwargs)


class Category(MPTTModel):
    title = models.CharField(max_length=255, verbose_name='Назва категорії')
    slug = models.SlugField(max_length=255, verbose_name='URL', unique=True)
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        db_index=True,
        related_name='children',
        verbose_name='Батьківська категорія'
    )

    class MPTTMeta:
        order_insertion_by = ('title',)

    class Meta:
        verbose_name = 'Категорія'
        verbose_name_plural = 'Категорії'

    def __str__(self):
        return ''.join([ancestor.title + ' > ' for ancestor in self.get_ancestors(include_self=True)])[:-3]

service/teach/models.py
from django.db import models

# Create your models here.

service/teach/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Checkbox

from services.models import Course, CourseInfo, CourseModules


class CourseCreateForm(forms.ModelForm):
    course_name = forms.CharField(min_length=3, max_length=50)
    captcha = ReCaptchaField(widget= ReCaptchaV2Checkbox(), required=True)
    class Meta:
        model = Course
        fields = ('course_name',)

class CourseUpdateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course_name', 'cat', 'description', 'language', 'difficulty', 'preview']

class CourseInfoUpdateForm(forms.ModelForm):
    class Meta:
        model = CourseInfo
        fields = ['workload', 'authors', 'preview_video']


class CourseModuleForm(forms.ModelForm):
    class Meta:
        model = CourseModules
        fields = ['title', 'description', 'order']

service/teach/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import *
from rest_framework.decorators import action
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import *
from rest_framework.generics import *
from rest_framework.viewsets import ModelViewSet

from catalog.utils import CourseFilter
from clients.serializers import ClientSerializer
from services.models import Course, CourseInfo, CourseModules
from teach.forms import CourseCreateForm, CourseUpdateForm, CourseInfoUpdateForm
from teach.mixins import OwnerPermissionMixin
from teach.repositories.course import CourseRepository
from teach.serializers import CourseUpdateSerializer
from teach.services.course import CourseService
import json


class TeachPromoView(TemplateView):
    # def dispatch(self, request, *args, **kwargs):
    #     if not request.user.:
    #         return redirect('accounts:login')
    #     return super().dispatch(request, *args, **kwargs)

    template_name = 'teach/teach_promo.html'


class TeachCoursesView(LoginRequiredMixin, ListView):
    template_name = 'teach/teach_courses_list.html'
    model = Course
    context_object_name = 'courses'

    def get_queryset(self):
        courses = Course.objects.filter(owner=self.request.user).only('id', 'course_name', 'preview',
                                                                      'full_price').order_by('-created_at')
        filtered_qs = CourseFilter(self.request.GET, queryset=courses)
        return filtered_qs.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = CourseFilter(self.request.GET, queryset=self.get_queryset())
        return context


class TeachCourseCreate(LoginRequiredMixin, CreateView):
    model = Course
    form_class = CourseCreateForm
    template_name = 'teach/teach_course_create.html'
    success_url = reverse_lazy('teach:courses')

    def form_valid(self, form):
        messages.success(self.request, f'Курс {form.instance.course_name} створено')
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, form.errors)
        return super().form_invalid(form)


class TeachCourseInfoEditView(LoginRequiredMixin, OwnerPermissionMixin, DetailView):
    model = Course
    template_name = 'teach/teach_course_edit.html'
    context_object_name = 'course'
    form_class = CourseUpdateForm

    def get_course(self, queryset=None):
        return Course.objects.select_related('owner', 'info').get(pk=self.kwargs['pk'])

    def get(self, request, *args, **kwargs):
        course = self.get_course()
        _ = CourseInfo.objects.get_or_create(course=course)[0]

        return render(request, self.template_name, {
            'course': course,
        })



class TeachCoursesSearchView(TemplateView):
    template_name = 'includes/teach_included_courses_list.html'

    def get(self, request, *args, **kwargs):
        courses = Course.objects.filter(owner=self.request.user).only('id', 'course_name', 'preview', 'is_published')
        filtered_qs = CourseFilter(self.request.GET, queryset=courses)

        context = {'courses': filtered_qs.qs}
        html = render_to_string(self.template_name, context)
        return JsonResponse(html, safe=False)


class UpdateCourseView(ModelViewSet):
    permission_classes = (IsAuthenticated, OwnerPermissionMixin)
    parser_classes = (MultiPartParser, FormParser)
    serializer_class = CourseUpdateSerializer
    queryset = Course.objects.all()
    service = CourseService(CourseRepository())

    def get_object(self):
        return Course.objects.select_related('owner', 'info').get(pk=self.kwargs['pk'])

    def update(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', False)
        instance = self.get_object()

        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        if serializer.is_valid(raise_exception=True):
            updated_course = self.service.update_course(instance.id, serializer.validated_data)
            return Response(CourseUpdateSerializer(updated_course).data)
        else:
            return Response(serializer.errors, status=400)

    @action(methods=['PUT'], detail=True)
    def update_authors(self, request, *args, **kwargs):
        instance = self.get_object()
        authors = request.data.get('authors')
        try:
            self.service.update_authors(instance.info, authors)
        except ValueError as e:
            return Response({"authors": [str(e)]}, status=400)  # Вернуть ошибку как список
        return JsonResponse({'authors': ClientSerializer(instance.info.authors.all(), many=True).data})


    @action(methods=['PUT'], detail=True)
    def delete_authors(self, request, *args, **kwargs):
        instance = self.get_object()
        data = request.data.get('authors')
        try:
            self.service.update_authors(instance.info, data, is_delete=True)
        except ValueError as e:
            return Response({"info": [str(e)]}, status=400)  # Вернуть ошибку как список
        return JsonResponse({'authors': ClientSerializer(instance.info.authors.all(), many=True).data})

service/teach/templates/includes/teach_included_courses_list.html
{% load static %}

{% if courses %}
    {% for course in courses %}
        <div class="d-flex p-3 mb-4 border rounded">
            <a href="{{ course.get_absolute_url }}" class="text-decoration-none">
                <!-- Изображение -->
                {% if course.preview %}
                    <img src="{{ course.preview.url }}"
                         alt="{{ course.course_name }}"
                         class="img-fluid me-3 rounded card-image">
                {% else %}
                    <img src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg"
                         alt="{{ course.course_name }}"
                         class="img-fluid me-3 rounded card-image">
                {% endif %}
            </a>
            <div class="d-flex flex-column w-100 px-3">
                <div class="mb-auto">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="d-flex justify-content-between ">
                                <h3>{{ course.course_name }}</h3>
                                <div class="dropdown">
                                    <a class="text-dark dropdown-toggle" href="#" role="button"
                                       data-bs-toggle="dropdown" aria-expanded="false">
                                        <i class="fa-solid fa-ellipsis-vertical"></i>
                                    </a>

                                    <ul class="dropdown-menu">
                                        <li><a class="dropdown-item" href="{% url 'teach:course_edit_content' course.id %}">Редагувати
                                            зміст</a></li>
                                        <li><a class="dropdown-item" href="#">Видалити</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-12">
                        <div class="d-flex flex-column">

                            <a href="{% url 'teach:course_edit_info' course.id %}" class="purple-link">Редагувати опис</a>
                        </div>
                    </div>
                </div>
            </div>

        </div>


    {% endfor %}
    {# TODO for empty search res #}
{% else %}
    Створіть свій перший курс
{% endif %}

service/teach/templates/includes/teach_lesson_form.html
{% load static %}
<div class="accordion-item">

    <h2 class="accordion-header" id="lesson-heading-{{ lesson.id }}">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                data-bs-target="#lesson-collapse-{{ lesson.id }}" aria-expanded="false"
                aria-controls="lesson-collapse-{{ lesson.id }}">
            Урок: {% if lesson.title %}{{ lesson.title }}{% else %}{{ num }}{% endif %}
        </button>
    </h2>
    <div id="lesson-collapse-{{ lesson.id }}" class="accordion-collapse collapse"
         aria-labelledby="lesson-heading-{{ lesson.id }}" data-bs-parent="#lessonsAccordion-{{ module.id }}">
        <div class="accordion-body">
            <form class=" needs-validation" method="post" id="lesson-form-{{ lesson.id }}"
                  data-lesson-id="{{ lesson.id }}" novalidate>
                {% csrf_token %}
                <input class="form-control mb-3" type="text" placeholder="Назва"
                       id="id_title_lesson_{{ lesson.id }}"
                       value="{% if lesson.title %}{{ lesson.title }}{% else %}{% endif %}"
                       required>

                <div class="invalid-feedback">
                    Назва уроку обов'язкова.
                </div>

                <button class="form-control mb-3 button-3" type="submit"
                        name="submit-lesson" id="submit-lesson-button-{{ lesson.id }}">Створити урок
                </button>
            </form>
        </div>
    </div>
</div>
<script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
<script>
    $(document).ready(function () {
        $('#lesson-form-{{ lesson.id }}').on('submit', function (event) {
            event.preventDefault();
            const lesson_id = $(this).data('lesson-id').toString();
            const csrf_token = document.getElementById('csrf_token').value;
            const lesson_title = document.getElementById('id_title_lesson_{{ lesson.id }}').value;
            if (!lesson_title.trim()) {
                return;
            }

            $.ajax({
                url: "{% url 'teach:lesson-detail' course.id %}",
                type: "PUT",
                data: JSON.stringify({
                    lesson_id: lesson_id,
                    title: lesson_title,
                }),
                headers: {
                    'X-CSRFToken': csrf_token
                },
                processData: false,
                contentType: 'application/json',
                success: function (response) {

                },
                error: function (xhr) {
                    console.log(xhr);
                }
            });
        });
    });
</script>

service/teach/templates/includes/teach_module_form.html
{#<form class="module-form-{{ module.id }}">#}
{#    <input type="text" name="title" placeholder="Назва" id="id_title">#}
{#    <textarea name="description" placeholder="Опис" id="id_description"></textarea>#}
{#    <input type="number" name="order" placeholder="Порядок" id="id_order">#}
{#    <button type="button" data-module-id="{{ module.id }}" name="create-lesson">Create lesson</button>#}
{#    {% if module.lessons %}#}
{#        {% for lesson in module.lessons.all %}#}
{#        <form class="lesson-form-{{ lesson.id }}">#}
{#            <input type="text" name="title" placeholder="Назва" id="id_title">#}
{#            <button type="submit" data-lesson-id="{{ lesson.id }}" name="submit-lesson">Створити урок</button>#}
{#        </form>#}
{#        {% endfor %}#}
{#    {% endif %}#}
{##}
{#</form>#}
{##}
{#<div class="accordion" id="accordionPanelsStayOpenExample">#}
{#  <div class="accordion-item">#}
{#    <h2 class="accordion-header">#}
{#      <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="true" aria-controls="panelsStayOpen-collapseOne">#}
{#        Accordion Item #1#}
{#      </button>#}
{#    </h2>#}
{#    <div id="panelsStayOpen-collapseOne" class="accordion-collapse collapse show">#}
{#      <div class="accordion-body">#}
{#          1#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{#  <div class="accordion-item">#}
{#    <h2 class="accordion-header">#}
{#      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseTwo" aria-expanded="false" aria-controls="panelsStayOpen-collapseTwo">#}
{#        Accordion Item #2#}
{#      </button>#}
{#    </h2>#}
{#    <div id="panelsStayOpen-collapseTwo" class="accordion-collapse collapse">#}
{#      <div class="accordion-body">#}
{#          2#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{#  <div class="accordion-item">#}
{#    <h2 class="accordion-header">#}
{#      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseThree" aria-expanded="false" aria-controls="panelsStayOpen-collapseThree">#}
{#        Accordion Item #3#}
{#      </button>#}
{#    </h2>#}
{#    <div id="panelsStayOpen-collapseThree" class="accordion-collapse collapse">#}
{#      <div class="accordion-body">#}
{#          3#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{#</div>#}


<div class="accordion mb-30" id="modulesAccordion">

    <div class="accordion-item ">
        <h2 class="accordion-header" id="module-heading-{{ module.id }}">
            <button class="accordion-button collapsed p-0 mb-4" type="button" data-bs-toggle="collapse" data-bs-target="#module-collapse-{{ module.id }}" aria-expanded="false" aria-controls="module-collapse-{{ module.id }}">
                <h1>Модуль: {% if module.title  %}{{ module.title }}{% else %}{{ num }}{% endif %}</h1>
            </button>
        </h2>
        <div id="module-collapse-{{ module.id }}" class="accordion-collapse collapse show" aria-labelledby="module-heading-{{ module.id }}" data-bs-parent="#modulesAccordion">
            <div class="accordion-body-{{ module.id }}">
                <form class="module-form-{{ module.id }}">
                    <input class="form-control mb-3" type="text" name="title" placeholder="Назва" id="id_title_module_{{ module.id }}" value="{% if module.title %}{{ module.title }}{% else %}Новий модуль{% endif %}">
                    <textarea class="form-control mb-3" name="description" placeholder="Опис" id="id_description_module_{{ module.id }}">{% if module.description %}{{ module.description }}{% else %}{% endif %}</textarea>
                    <input class="form-control mb-3" type="number" name="order" placeholder="Порядок" id="id_order_module_{{ module.id }}" value="{{ module.order }}">
                    <button class="button-3 mb-3" type="button" data-module-id="{{ module.id }}" name="create-lesson"><i class="fa-solid fa-plus"></i>Додати урок</button>
                </form>

                {% if module.lessons %}
                <div class="accordion mt-3" id="lessonsAccordion-{{ module.id }}">
                    {% for lesson in module.lessons.all %}
                    {% include 'includes/teach_lesson_form.html' with lesson=lesson num=forloop.counter%}
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
</div>

service/teach/templates/includes/teach_sidepanel.html
{% load static %}

<div class="col-md-3 border-end ">
    <div class="d-flex flex-column sticky-top stick-filter d-none d-md-flex">
        <a href="{% url 'teach:create_course' %}" class="purple-link">Створити курс</a>
    </div>
</div>