service/service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from clients.views import SendActivationEmailView

from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('accounts/', include('allauth.urls')),

    path('', include('services.urls', namespace='services')),
    path('clients/', include('clients.urls', namespace='clients')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('teach/', include('teach.urls', namespace='teach')),

    path('api/send_activation_email/', SendActivationEmailView.as_view(), name='send_activation_email_api'),

]+ debug_toolbar_urls()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

service/teach/urls.py
from django.urls import path
from rest_framework import routers

from teach.course_content_edit import TeachCourseModulesView, CreateModuleAPI, CreateLessonAPI
from teach.views import *

app_name = 'teach'


router = routers.SimpleRouter()
router.register('api/v1/course_edit_info', UpdateCourseView)
router.register('api/v1/course_edit_content_module', CreateModuleAPI)
router.register('api/v1/course_edit_content_lesson', CreateLessonAPI)



urlpatterns = [
    path('', TeachPromoView.as_view(), name='teach_promo'),
    path('courses/', TeachCoursesView.as_view(), name='courses'),
    path('courses/new/', TeachCourseCreate.as_view(), name='create_course'),
    path('courses/edit-info/<int:pk>/', TeachCourseInfoEditView.as_view(), name='course_edit_info'),
    path('courses/edit-content/<int:pk>/', TeachCourseModulesView.as_view(), name='course_edit_content'),
    # path('courses/edit-content/<int:pk>/', TeachCourseModulesView.as_view(), name='course_edit_content'),

    path('api/v1/teach-search/', TeachCoursesSearchView.as_view(), name='course_search'),
]+router.urls

service/teach/models.py
from django.db import models

# Create your models here.

service/teach/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV2Checkbox

from services.models import Course, CourseInfo, CourseModules


class CourseCreateForm(forms.ModelForm):
    course_name = forms.CharField(min_length=3, max_length=50)
    captcha = ReCaptchaField(widget= ReCaptchaV2Checkbox(), required=True)
    class Meta:
        model = Course
        fields = ('course_name',)

class CourseUpdateForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['course_name', 'cat', 'description', 'language', 'difficulty', 'preview']

class CourseInfoUpdateForm(forms.ModelForm):
    class Meta:
        model = CourseInfo
        fields = ['workload', 'authors', 'preview_video']


class CourseModuleForm(forms.ModelForm):
    class Meta:
        model = CourseModules
        fields = ['title', 'description', 'order']

service/teach/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import *
from rest_framework.decorators import action
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import *
from rest_framework.generics import *
from rest_framework.viewsets import ModelViewSet

from catalog.utils import CourseFilter
from clients.serializers import ClientSerializer
from services.models import Course, CourseInfo, CourseModules
from teach.forms import CourseCreateForm, CourseUpdateForm, CourseInfoUpdateForm
from teach.mixins import OwnerPermissionMixin
from teach.repositories.course import CourseRepository
from teach.serializers import CourseUpdateSerializer
from teach.services.course import CourseService
import json


class TeachPromoView(TemplateView):
    # def dispatch(self, request, *args, **kwargs):
    #     if not request.user.:
    #         return redirect('accounts:login')
    #     return super().dispatch(request, *args, **kwargs)

    template_name = 'teach/teach_promo.html'


class TeachCoursesView(LoginRequiredMixin, ListView):
    template_name = 'teach/teach_courses_list.html'
    model = Course
    context_object_name = 'courses'

    def get_queryset(self):
        courses = Course.objects.filter(owner=self.request.user).only('id', 'course_name', 'preview',
                                                                      'full_price').order_by('-created_at')
        filtered_qs = CourseFilter(self.request.GET, queryset=courses)
        return filtered_qs.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = CourseFilter(self.request.GET, queryset=self.get_queryset())
        return context


class TeachCourseCreate(LoginRequiredMixin, CreateView):
    model = Course
    form_class = CourseCreateForm
    template_name = 'teach/teach_course_create.html'
    success_url = reverse_lazy('teach:courses')

    def form_valid(self, form):
        messages.success(self.request, f'Курс {form.instance.course_name} створено')
        form.instance.owner = self.request.user
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, form.errors)
        return super().form_invalid(form)


class TeachCourseInfoEditView(LoginRequiredMixin, OwnerPermissionMixin, DetailView):
    model = Course
    template_name = 'teach/teach_course_edit.html'
    context_object_name = 'course'
    form_class = CourseUpdateForm

    def get_course(self, queryset=None):
        return Course.objects.select_related('owner', 'info').get(pk=self.kwargs['pk'])

    def get(self, request, *args, **kwargs):
        course = self.get_course()
        _ = CourseInfo.objects.get_or_create(course=course)[0]

        return render(request, self.template_name, {
            'course': course,
        })



class TeachCoursesSearchView(TemplateView):
    template_name = 'includes/teach_included_courses_list.html'

    def get(self, request, *args, **kwargs):
        courses = Course.objects.filter(owner=self.request.user).only('id', 'course_name', 'preview', 'is_published')
        filtered_qs = CourseFilter(self.request.GET, queryset=courses)

        context = {'courses': filtered_qs.qs}
        html = render_to_string(self.template_name, context)
        return JsonResponse(html, safe=False)


class UpdateCourseView(ModelViewSet):
    permission_classes = (IsAuthenticated, OwnerPermissionMixin)
    parser_classes = (MultiPartParser, FormParser)
    serializer_class = CourseUpdateSerializer
    queryset = Course.objects.all()
    service = CourseService(CourseRepository())

    def get_object(self):
        return Course.objects.select_related('owner', 'info').get(pk=self.kwargs['pk'])

    def update(self, request, *args, **kwargs):
        partial = kwargs.pop('partial', False)
        instance = self.get_object()

        serializer = self.get_serializer(instance, data=request.data, partial=partial)
        if serializer.is_valid(raise_exception=True):
            updated_course = self.service.update_course(instance.id, serializer.validated_data)
            return Response(CourseUpdateSerializer(updated_course).data)
        else:
            return Response(serializer.errors, status=400)

    @action(methods=['PUT'], detail=True)
    def update_authors(self, request, *args, **kwargs):
        instance = self.get_object()
        authors = request.data.get('authors')
        try:
            self.service.update_authors(instance.info, authors)
        except ValueError as e:
            return Response({"authors": [str(e)]}, status=400)  # Вернуть ошибку как список
        return JsonResponse({'authors': ClientSerializer(instance.info.authors.all(), many=True).data})


    @action(methods=['PUT'], detail=True)
    def delete_authors(self, request, *args, **kwargs):
        instance = self.get_object()
        data = request.data.get('authors')
        try:
            self.service.update_authors(instance.info, data, is_delete=True)
        except ValueError as e:
            return Response({"info": [str(e)]}, status=400)  # Вернуть ошибку как список
        return JsonResponse({'authors': ClientSerializer(instance.info.authors.all(), many=True).data})

service/teach/templates/teach/teach_base.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="marco-layout">
        <div class="container-fluid">
            <div class="row">
                {% block sidepanel %}
                    {% include 'includes/teach_sidepanel.html' %}
                {% endblock %}

                {% block teach_layout %}
                {% endblock %}
            </div>
        </div>
    </div>

{% endblock %}

service/teach/templates/teach/teach_course_create.html
{% extends 'teach/teach_base.html' %}

{% load static %}

{% block teach_layout %}
    <div class="col-md-9">
        <div class="catalog-main-content">
            <form id="course-form" action="{% url 'teach:create_course' %}" method="post">
                {% csrf_token %}
                {% if form.captcha.errors %}
                    <div class="alert alert-danger alert-dismissible pb-0 captcha-error" role="alert">
                        <div class="form-error-1 text-center">Ви не пройшли перевірку на робота</div>
                        <button type="button" class="btn-close" data-bs-dismiss="alert"
                                aria-label="Close"></button>
                    </div>
                {% endif %}
                <div class="mb-3">
                    <label for="id_course_name">Назва курсу:</label>
                    <input type="text" class="form-control" name="course_name" maxlength="255" required=""
                           id="id_course_name">
                </div>

                <div id="captcha-container" class="mb-3" style="display:none;">
                    {{ form.captcha }}
                </div>

                <button type="submit" class="button-3" id="submit-btn">Створити</button>
            </form>
        </div>
    </div>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const submitBtn = document.getElementById('submit-btn');
            const captchaContainer = document.getElementById('captcha-container');
            let captchaVisible = false;

            // Слушаем нажатие на кнопку сабмита
            submitBtn.addEventListener('click', function (event) {

                if (!captchaVisible) {
                    event.preventDefault();  // Останавливаем отправку формы
                    captchaContainer.style.display = 'block';  // Показываем капчу
                    captchaVisible = true;  // Теперь капча видна
                }
            });

        });
    </script>
{% endblock %}

service/teach/templates/teach/teach_course_modules.html
{% extends 'teach/teach_base.html' %}

{% load static %}

{% block teach_layout %}
    <div class="col-md-9">
        <div class="catalog-main-content">
            <div id="modules-container">
                <input id="csrf_token" type="hidden" value="{{ csrf_token }}">
                {% if not modules %}
                    Створіть перший модуль
                {% endif %}
                {% for module in modules %}

                    {% include 'includes/teach_module_form.html' with module=module num=forloop.counter %}

                    <hr class="border border-2 opacity-50">

                {% endfor %}

            </div>
            <button type="button" name="create-module" class="button-3"><i class="fa-solid fa-plus"></i> Додати модуль
            </button>
        </div>
    </div>

    <script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('button[name="create-module"]').click(function (event) {
                event.preventDefault();
                const csrf_token = document.getElementById('csrf_token').value;

                $.ajax({
                    url: "{% url 'teach:coursemodules-detail' course.id %}",
                    type: "POST",
                    data: null,
                    headers: {
                        'X-CSRFToken': csrf_token  // Используем извлеченный CSRF-токен
                    },
                    processData: false,
                    contentType: false,
                    success: function (response) {
                        $('#modules-container').append(response.module_form);
                    },
                    error: function (xhr) {
                        console.log(xhr);
                    }
                });
            });

            $('button[name="create-lesson"]').click(function (event) {
                event.preventDefault();
                const csrf_token = document.getElementById('csrf_token').value;
                const module_id = $(this).data('module-id').toString();

                $.ajax({
                    url: "{% url 'teach:lesson-detail' course.id %}",
                    type: "POST",
                    data: JSON.stringify({module_id: module_id}),
                    headers: {
                        'X-CSRFToken': csrf_token
                    },
                    processData: false,
                    contentType: 'application/json',
                    success: function (response) {
                        $('.accordion-body-' + module_id).append(response.lesson_form);
                    },
                    error: function (xhr) {
                        console.log(xhr);
                    }
                });
            });





        });


    </script>

{% endblock %}

service/teach/templates/teach/teach_courses_list.html
{% extends 'teach/teach_base.html' %}

{% load static %}

{% block teach_layout %}
    <div class="col-md-9">
        <div class="catalog-main-content">
            <div class="catalog-search-bar">
                <div class="d-flex flex-row justify-content-center align-items-center catalog-search-form">
                    <form method="get" class="search-form d-flex align-items-center flex-fill"
                          id="teach-courses-search-form">
                        <div class="d-flex me-3">
                            <select class="nice-select" name="status" tabindex="0">
                                    <option value="0" class="option selected">Всі</option>
                                    <option value="1" class="option ">Опублікувані</option>
                                    <option value="2" class="option focus">Чернетки</option>
                            </select>
                        </div>
                        <div class="input-group flex-fill me-3">
                                        <span class="input-group-text"><i
                                                class="fa-solid fa-magnifying-glass"></i></span>

                            <input type="text" name="q" placeholder="Пошук..."
                                   class="form-control search-input"
                                   value="{{ request.GET.q }}">
                            <input type="hidden" value="{{ request.user.id }}" id="user_owner">
                        </div>
                        <div class="d-none d-md-flex">
                            <button class="button-3 flex-fill me-3">Пошук</button>
                        </div>
                        <div class="d-flex d-md-none">
                            <button class="filters-btn" type="button" data-bs-toggle="offcanvas"
                                    data-bs-target="#offcanvasWithBothOptions"
                                    aria-controls="offcanvasWithBothOptions"><i
                                    class="fa-solid fa-filter"></i>
                            </button>
                        </div>

                    </form>


                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="courses-list">
                        {% include 'includes/teach_included_courses_list.html' %}

                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

service/teach/templates/teach/teach_promo.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
        <div class="catalog">
        teach promo


<div class="text-center">
            <a href="{% url 'teach:courses' %}" class="button-3 text-center">Створити курс</a>
    </div>
        </div>
{% endblock content %}