service/catalog/urls.py
from django.urls import path
from .views import *

app_name = 'catalog'

urlpatterns = [
    path('', CatalogMainView.as_view(), name='catalog'),
    path('search/', CatalogListView.as_view(), name='search-catalog'),

    path('api/v1/search/', SearchView.as_view(), name='search'),
    path('api/v1/get-courses/', GetCoursesView.as_view(), name='get_courses'),
]

service/clients/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from .views import *

app_name = 'clients'

urlpatterns = [
    path('register/', RegisterClientView.as_view(), name='register'),
    path('login/', ClientLoginView.as_view(), name='login'),
    path('profile/', ClientProfileView.as_view(), name='profile'),
    path('logout/', logout_user, name='logout'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),

]

service/service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from clients.views import SendActivationEmailView

from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('accounts/', include('allauth.urls')),

    path('', include('services.urls', namespace='services')),
    path('clients/', include('clients.urls', namespace='clients')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('teach/', include('teach.urls', namespace='teach')),

    path('api/send_activation_email/', SendActivationEmailView.as_view(), name='send_activation_email_api'),

]+ debug_toolbar_urls()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

service/services/urls.py
from django.urls import path
from .views import *


app_name = 'services'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('course/<int:pk>/', CourseDetailView.as_view(), name='course_detail'),


]

service/teach/urls.py
from django.urls import path
from rest_framework import routers

from teach.course_content_edit import TeachCourseModulesView, CreateModuleAPI, CreateLessonAPI
from teach.views import *

app_name = 'teach'


router = routers.SimpleRouter()
router.register('api/v1/course_edit_info', UpdateCourseView)
router.register('api/v1/course_edit_content_module', CreateModuleAPI)
router.register('api/v1/course_edit_content_lesson', CreateLessonAPI)



urlpatterns = [
    path('', TeachPromoView.as_view(), name='teach_promo'),
    path('courses/', TeachCoursesView.as_view(), name='courses'),
    path('courses/new/', TeachCourseCreate.as_view(), name='create_course'),
    path('courses/edit-info/<int:pk>/', TeachCourseInfoEditView.as_view(), name='course_edit_info'),
    path('courses/edit-content/<int:pk>/', TeachCourseModulesView.as_view(), name='course_edit_content'),
    # path('courses/edit-content/<int:pk>/', TeachCourseModulesView.as_view(), name='course_edit_content'),

    path('api/v1/teach-search/', TeachCoursesSearchView.as_view(), name='course_search'),
]+router.urls

service/templates/includes/access_denied.html
{% extends 'base.html' %}

{% block header %}
{% endblock %}

{% block content %}
    <div class="container mt-3">
        <div class="row justify-content-center m-4">
            <div class="col-md-6">
                <h1 style="font-size: 42px;">Невдалося виконати запит, помилка </h1>
                <h1 class="text-danger" style="font-size: 82px;">{{ status }}</h1>

            <h1>{{ error }}</h1>
                </div>
        </div>
    </div>

{% endblock %}

service/templates/includes/footer.html
<footer>
    <div class="footer-wrappper footer-bg">
        <!-- Footer Start-->
        <div class="footer-area footer-padding">
            <div class="container">
                <div class="row justify-content-between">
                    <div class="col-xl-4 col-lg-5 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="single-footer-caption mb-30">
                                <!-- logo -->
                                <div class="footer-logo mb-25">
                                    <a href="{% url 'services:index' %}"><img src="assets/img/logo/logo2_footer.png" alt=""></a>
                                </div>
                                <div class="footer-tittle">
                                    <div class="footer-pera">
                                        <p>The automated process starts as soon as your clothes go into the machine.</p>
                                    </div>
                                </div>
                                <!-- social -->
                                <div class="footer-social">
                                    <a href="#"><i class="fab fa-twitter"></i></a>
                                    <a href="https://bit.ly/sai4ull"><i class="fab fa-facebook-f"></i></a>
                                    <a href="#"><i class="fab fa-pinterest-p"></i></a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-5">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Our solutions</h4>
                                <ul>
                                    <li><a href="#">Design & creatives</a></li>
                                    <li><a href="#">Telecommunication</a></li>
                                    <li><a href="#">Restaurant</a></li>
                                    <li><a href="#">Programing</a></li>
                                    <li><a href="#">Architecture</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-4 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Support</h4>
                                <ul>
                                    <li><a href="#">Design & creatives</a></li>
                                    <li><a href="#">Telecommunication</a></li>
                                    <li><a href="#">Restaurant</a></li>
                                    <li><a href="#">Programing</a></li>
                                    <li><a href="#">Architecture</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-2 col-lg-3 col-md-4 col-sm-6">
                        <div class="single-footer-caption mb-50">
                            <div class="footer-tittle">
                                <h4>Company</h4>
                                <ul>
                                    <li><a href="#">Design & creatives</a></li>
                                    <li><a href="#">Telecommunication</a></li>
                                    <li><a href="#">Restaurant</a></li>
                                    <li><a href="#">Programing</a></li>
                                    <li><a href="#">Architecture</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- footer-bottom area -->
        <div class="footer-bottom-area">
            <div class="container">
                <div class="footer-border">
                    <div class="row d-flex align-items-center">
                        <div class="col-xl-12 ">
                            <div class="footer-copy-right text-center">
                                <p>
                                    Copyright &copy;<script>document.write(new Date().getFullYear());</script>
                                    All rights reserved
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Footer End-->
    </div>
</footer>

service/templates/includes/navbar-transparent.html
{% load static %}
{% load teach_tags %}
<header>
    <!-- Header Start -->
    <div class="header-area header-transparent " style="background-color: #2c2c2c">
        <div class="main-header ">
            <div class="header-bottom  header-sticky">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <!-- Logo -->
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo">
                                <a href="{% url 'services:index' %}" class="logo">
                                    /selfedu<br>

                                </a>
                            </div>
                        </div>
                        <div class="col-xl-10 col-lg-10">
                            <div class="menu-wrapper d-flex align-items-center justify-content-end">
                                <!-- Main-menu -->
                                <div class="main-menu d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="{% url 'catalog:catalog' %}">Курси</a></li>
                                        {% if request.is_authenticated %}
                                            {% has_courses request.user as user_has_courses %}
                                        {% endif %}
                                            <li>
                                                <a href="{% if user_has_courses %}{% url 'teach:courses' %}{% else %}{% url 'teach:teach_promo' %}{% endif %}">
                                                    Викладання
                                                </a>
                                            </li>
                                            <li><a href="contact.html">Співробітництво</a></li>
                                            <!-- Button -->
                                            {% if not request.user.is_authenticated %}
                                            <li class="button-header margin-left "><a href="{% url 'clients:register' %}" class="btn btn3">Регістрація</a>
                                            </li>
                                            <li class="button-header"><a href="{% url 'clients:login' %}" class="btn btn3">Вхід</a>
                                            </li>
                                            {% else %}
                                            <li class="button-header"><a href="{% url 'clients:logout' %}" class="btn btn3">Вихід</a>
                                            </li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
</header>

service/templates/includes/navbar.html
{% load static cache %}
{% load teach_tags %}

<header>
    <!-- Header Start -->

    <div class="header-area bg-dark fixed-top">
        <div class="main-header ">
            <div class="header-bottom  ">
                <div class="container-fluid">
                    <div class="row align-items-center">
                        <!-- Logo -->
                        <div class="col-xl-2 col-lg-2">
                            <div class="logo">
                                <a href="{% url 'services:index' %}" class="logo">
                                    /selfedu<br>

                                </a>
                            </div>
                        </div>
                        <div class="col-xl-10 col-lg-10">
                            <div class="menu-wrapper d-flex align-items-center justify-content-end">
                                <!-- Main-menu -->
                                <div class="main-menu d-none d-lg-block">
                                    <nav>
                                        <ul id="navigation">
                                            <li><a href="{% url 'catalog:catalog' %}">Курси</a></li>
                                            {% cache 3600 'have_courses-{{ request.user.id }}' %}
                                                {% if request.is_authenticated %}
                                                    {% has_courses request.user as user_has_courses %}
                                                {% endif %}
                                                <li>
                                                    <a href="
                                                            {% if user_has_courses %}{% url 'teach:courses' %}{% else %}{% url 'teach:teach_promo' %}{% endif %}">
                                                        Викладання
                                                    </a>
                                                </li>
                                            {% endcache %}
                                            <li><a href="contact.html">Співробітництво</a></li>
                                            <!-- Button -->

                                            {% if not request.user.is_authenticated %}
                                                <li class="button-header margin-left "><a
                                                        href="{% url 'clients:register' %}"
                                                        class="btn btn3">Регістрація</a>
                                                </li>
                                                <li><a href="{% url 'clients:login' %}"
                                                       class="btn btn3">Вхід</a>
                                                </li>
                                            {% else %}
                                                <li><a href="{% url 'clients:logout' %}">Вихід</a>
                                                </li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                </div>
                            </div>
                        </div>
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Header End -->
</header>

service/templates/includes/notifications.html
{% load static %}

{% if form.non_field_errors %}
<div class="container mt-4">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <div class="alert alert-danger alert-dismissible" role="alert">
                {% for error in form.non_field_errors %}
                <div class="form-error-1 text-center mt-2">
                    {{ error }}
                </div>
                {% endfor %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        </div>
    </div>
</div>
{% endif %}


<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            {% if messages %}
            {% for message in messages %}
            {% if message.tags == 'success' %}
            <div id="notification"
                 class="mt-3 position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow"
                 role="alert" style="z-index: 99999; top: 100px;">
                {{ message }}
            </div>
            {% endif %}
            {% if message.tags == 'warning' %}
            <div id="notification"
                 class="mt-3 position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show"
                 style="z-index: 99999; top: 100px;" role="alert">
                {{ message }}
            </div>
            {% endif %}
            {% endfor %}
            {% else %}
            <div id="jq-notification"
                 class="mt-3 position-fixed start-50 translate-middle-x z-3 alert alert-success fade show custom-shadow"
                 style="display: none; z-index: 99999; top: 100px;" role="alert">
            </div>
            <div id="warning-jq-notification"
                 class="mt-3 position-fixed start-50 translate-middle-x z-3 alert alert-danger fade show custom-shadow"
                 style="display: none; z-index: 99999; top: 100px;" role="alert">
            </div>
            {% endif %}
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function () {
        var errors = document.querySelectorAll('.alert .form-error-1');
        errors.forEach(function (error) {
            if (error.textContent.includes('Ваш обліковий запис неактивний')) {
                var link = document.createElement('a');
                link.href = "{% url 'clients:register' %}";
                link.className = "text-decoration-none text-danger";
                link.textContent = "Надішліть підтвердження ще раз";

                const toEmail = document.getElementById('id_username').value;
                link.addEventListener('click', function (event) {
                    event.preventDefault();
                    sendActivationEmail(toEmail);
                });


                // Создаем новый элемент с текстом и ссылкой
                var additionalText = document.createElement('p');
                // Вставляем текст и ссылку в элемент ошибки
                error.appendChild(additionalText);
                error.appendChild(link);

            }
        });
    });

   function sendActivationEmail(toEmail) {
        const data = {
            subject: 'Підтвердження реєстрації',
            to_email: toEmail
        };

        $.ajax({
            url: '{% url "send_activation_email_api" %}',
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'  // Добавляем CSRF токен
            },
            contentType: 'application/json',
            data: JSON.stringify(data),
            success: function (response) {
                if (response.status === 'success') {
                    window.location.href = "{% url 'clients:login' %}";
                } else {
                    alert('Ошибка: ' + JSON.stringify(response));
                }
            },
            error: function (xhr, status, error) {
                console.error('Ошибка:', error);
            }
        });
    }



</script>