service/clients/urls.py
from django.contrib.auth.views import PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path

from .views import *

app_name = 'clients'

urlpatterns = [
    path('register/', RegisterClientView.as_view(), name='register'),
    path('login/', ClientLoginView.as_view(), name='login'),
    path('profile/', ClientProfileView.as_view(), name='profile'),
    path('logout/', logout_user, name='logout'),
    path('activate/<uidb64>/<token>/', activate, name='activate'),

]

service/service/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from rest_framework.routers import SimpleRouter

from clients.views import SendActivationEmailView

from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('djoser.urls')),
    path('auth/', include('djoser.urls.jwt')),
    path('accounts/', include('allauth.urls')),

    path('', include('services.urls', namespace='services')),
    path('clients/', include('clients.urls', namespace='clients')),
    path('catalog/', include('catalog.urls', namespace='catalog')),
    path('teach/', include('teach.urls', namespace='teach')),

    path('api/send_activation_email/', SendActivationEmailView.as_view(), name='send_activation_email_api'),

]+ debug_toolbar_urls()


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

service/teach/urls.py
from django.urls import path
from rest_framework import routers

from teach.course_content_edit import TeachCourseModulesView, CreateModuleAPI, CreateLessonAPI
from teach.views import *

app_name = 'teach'


router = routers.SimpleRouter()
router.register('api/v1/course_edit_info', UpdateCourseView)
router.register('api/v1/course_edit_content_module', CreateModuleAPI)
router.register('api/v1/course_edit_content_lesson', CreateLessonAPI)



urlpatterns = [
    path('', TeachPromoView.as_view(), name='teach_promo'),
    path('courses/', TeachCoursesView.as_view(), name='courses'),
    path('courses/new/', TeachCourseCreate.as_view(), name='create_course'),
    path('courses/edit-info/<int:pk>/', TeachCourseInfoEditView.as_view(), name='course_edit_info'),
    path('courses/edit-content/<int:pk>/', TeachCourseModulesView.as_view(), name='course_edit_content'),
    # path('courses/edit-content/<int:pk>/', TeachCourseModulesView.as_view(), name='course_edit_content'),

    path('api/v1/teach-search/', TeachCoursesSearchView.as_view(), name='course_search'),
]+router.urls

service/clients/models.py
from django.contrib.auth.base_user import BaseUserManager, AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, AbstractUser
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.contrib.auth.hashers import make_password

class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, password, **extra_fields)

class Client(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255, unique=True, validators=[UnicodeUsernameValidator()], blank=True, null=True)
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=255, blank=True)
    last_name = models.CharField(max_length=255, blank=True)
    # is_teacher = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_verified = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    def __str__(self):
        return self.email
    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

service/clients/forms.py
from allauth.account.forms import ResetPasswordForm
from django import forms
from django.contrib.auth import authenticate
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.core.validators import EmailValidator

from clients.models import Client
from clients.utils import validate_email, validate_username


class RegisterUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_confirm = forms.CharField(widget=forms.PasswordInput, label="Confirm Password")

    class Meta:
        model = Client
        fields = ('email', 'first_name', 'last_name', 'password')

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password_confirm = cleaned_data.get("password_confirm")

        if password and password_confirm and password != password_confirm:
            self.add_error('password_confirm', "Passwords do not match.")

    def clean_email(self):
        email = self.cleaned_data['email']
        validate_email(self, email)
        return email


class LoginUserForm(AuthenticationForm):
    class Meta:
        model = Client
        fields = ('email', 'password')

    def clean_username(self):
        email = self.cleaned_data['username']
        validate_username(email)
        return email

    def confirm_login_allowed(self, user):
        if not user.is_verified:
            raise forms.ValidationError("Ваш обліковий запис неактивний. Перевірте електронну пошту для підтвердження.",
                                        code='inactive', )

service/clients/views.py
from django.contrib import messages, auth
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.contrib.sites.shortcuts import get_current_site
from django.http import HttpResponseBadRequest
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.utils.http import urlsafe_base64_decode
from django.views import View
from django.views.generic import CreateView, UpdateView, DetailView
from rest_framework import status
from rest_framework.authtoken.models import Token
from rest_framework.response import Response
from rest_framework.views import APIView

from clients.forms import RegisterUserForm, LoginUserForm
from clients.models import Client
from clients.serializers import ActivationEmailSerializer
from clients.tasks import send_activation_email
from clients.utils import render_activation_email



def activate(request, uidb64, token):
    User = get_user_model()
    try:
        uid = urlsafe_base64_decode(uidb64).decode()
        user = User.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None

    if user is not None:
        try:
            token_obj = Token.objects.get(user=user)
            if token_obj.key == token:
                user.is_verified = True
                user.save()
                auth.login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                messages.success(request, f"Акаунт {user.email} активовано.")
                return redirect('services:index')
        except Token.DoesNotExist:
            pass

    return render(request, 'clients/activation_invalid.html')




class RegisterClientView(CreateView):
    template_name = 'clients/register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('services:index')

    def form_valid(self, form):
        user = form.save(commit=False)
        user.set_password(form.cleaned_data['password'])
        user.save()

        to_email = form.cleaned_data.get('email')
        message = render_activation_email(self.request, user.id)
        send_activation_email.delay('Підтвердження реєстрації', message, to_email)

        messages.success(self.request, f"Лист для активації відправлено на {to_email}. Перевірте вашу пошту.")
        return redirect(self.success_url)

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Реєстрація'
        return context

class ClientLoginView(LoginView):
    template_name = 'clients/login.html'
    form_class = LoginUserForm

    def dispatch(self, request, *args, **kwargs):
        if self.request.user.is_authenticated:
            messages.success(self.request, f"Ви вже авторизовані")
            return redirect('services:index')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        # redirect_page = self.request.POST.get('next', None)
        # if redirect_page and redirect_page != reverse('clients:logout'):
        #     return redirect_page
        return reverse_lazy('services:index')

    def form_valid(self, form):
        session_key = self.request.session.session_key
        user = form.get_user()

        if user:
            if not user.is_verified:
                messages.error(self.request, "Ваша електронна пошта не підтверджена.")
                return redirect('clients:login')

            auth.login(self.request, user)
            if session_key:
                #
                # forgotten_cart = Cart.objects.filter(user=user)
                # if forgotten_cart.exists():
                #     forgotten_cart.delete()
                #
                # Cart.objects.filter(session_key=session_key).update(user=user)
                messages.success(self.request, f"Ви авторизовані")

        return redirect(self.get_success_url())

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Авторизація'
        return context


@login_required
def logout_user(request):
    if request.user.is_authenticated:
        auth.logout(request)
        messages.success(request, 'Ви вийшли з акаунту')
        return redirect('services:index')

class ClientProfileView(LoginRequiredMixin, DetailView):
    template_name = 'clients/profile.html'
    context_object_name = 'client'
    def get_object(self, *args, **kwargs):
        return self.request.user
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class SendActivationEmailView(APIView):
    def post(self, request):
        serializer = ActivationEmailSerializer(data=request.data)
        if serializer.is_valid():
            data = serializer.validated_data

            user = Client.objects.get(email=data['to_email'])
            message = render_activation_email(self.request, user.id)

            send_activation_email.delay(data['subject'], message, data['to_email'])
            messages.success(request, f"Лист для активації відправлено на {data['to_email']}. Перевірте вашу пошту і увійдіть")
            return Response({'status': 'success'}, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

service/clients/templates/clients/activate_jwt.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="container text-center" data-animation="fadeInLeft" data-delay="0.4s">
    <button type="submit" class="btn btn1 " id="activate-btn">Активувати</button>
</div>
<input type="hidden" id="uid" name="uid" value="{{ uid }}">
<input type="hidden" id="token" name="token" value="{{ token }}">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>

    $(document).ready(function () {
        $('#activate-btn').on('click', function (event) {
            var uid = $('#uid').val();
            var token = $('#token').val();
            var data = JSON.stringify({uid: uid, token: token});
            $.ajax({
                url: '/auth/users/activation/',
                type: 'POST',
                contentType: 'application/json',
                data: data,
                success: function () {
                    console.log('ok activation');

                },
                error: function () {
                    console.log('error');
                },

            });
        });
    });
</script>
{% endblock content %}

service/clients/templates/clients/activation_email.html
    {% autoescape off %}  
    Hi {{ user.email }},
    Please click on the link to confirm your registration,  
    http://{{ domain }}{% url 'clients:activate' uidb64=uid token=token %}
    {% endautoescape %}  

service/clients/templates/clients/login.html
{% extends 'base.html' %}
{% load static %}
{% load account %}
{% load socialaccount %}


{% block content %}
    <div class="container" id="reg_container">
        <div class="d-flex justify-content-center my-3">
            <div class="col-md-6">

                <form id="loginForm" action="{% url 'clients:login' %}" method="post" content="application/json">

                    {% csrf_token %}

                    {% if request.GET.next %}
                        <input type="hidden" name="next" value="{{ request.GET.next }}">
                    {% endif %}
                
                    <label for="id_username" class="form-label">Email:</label>
                    {% if form.username.errors %}
                        <div class="alert alert-danger alert-dismissible pb-0" role="alert" style="top:50px;">
                            <div class="form-error-1 text-center">{{ form.username.errors }}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                    <input type="text" name="username"
                           value="{% if form.username.value %}{{ form.username.value }}{% endif %}" autofocus=""
                           autocapitalize="none"
                           autocomplete="username" maxlength="254" required="" id="id_username" class="form-control">


                    <div class="mb-3">
                        <label for="id_password" class="form-label">Введіть пароль</label>
                        {% if form.password.errors %}
                            <div class="alert alert-danger alert-dismissible pb-0" role="alert" style="top:50px;">
                                <div class="form-error-1 text-center">{{ form.password.errors }}</div>
                                <button type="button" class="btn-close" data-bs-dismiss="alert"
                                        aria-label="Close"></button>
                            </div>
                        {% endif %}
                        <input type="password" name="password" autocomplete="current-password" required=""
                               id="id_password" class="form-control">
                    </div>

                    <div class="d-flex justify-content-between">
                        <button type="submit" class="custom-btn btn-1">Вхід</button>
                    </div>
                </form>
                <a href="{% provider_login_url 'google' %}" class="btn">Увійти з Google</a>
            <a href="{% url 'account_reset_password' %}" class="text-dark">Забули пароль?</a>
            </div>
        </div>
    </div>

{% endblock content %}

service/clients/templates/clients/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <p>username {{ client.username }}</p>
    <p>email {{ client.email }}</p>
    <p>first name {{ client.first_name }}</p>
    <p>last name {{ client.last_name }}</p>
    <p>is_teacher {{ client.is_teacher }}</p>


{% endblock content %}

service/clients/templates/clients/register.html
{% extends 'base.html' %}

{% load static %}
{% load account %}
{% load socialaccount %}

{% block content %}
    <div class="container" id="reg_container">
        <div class="d-flex justify-content-center my-3">
            <div class="col-md-6">
                <form id="registerForm" action="{% url 'clients:register' %}" method="post" content="application/json">
                    {% csrf_token %}
                    <label for="id_email" class="form-label">Email:</label>
                    {% if form.email.errors %}
                        <div class="alert alert-danger alert-dismissible pb-0" role="alert" style="top:50px;">
                            <div class="form-error-1 text-center">{{ form.email.errors }}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                    <input type="email" name="email"
                           value="{% if form.email.value %}{{ form.email.value }}{% endif %}" autofocus=""
                           autocapitalize="none"
                           autocomplete="email" maxlength="254" required="" id="id_email" class="form-control">

                    <label for="id_first_name" class="form-label">first_name:</label>
                    {% if form.first_name.errors %}
                        <div class="alert alert-danger alert-dismissible pb-0" role="alert" style="top:50px;">
                            <div class="form-error-1 text-center">{{ form.first_name.errors }}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                    <input type="text" name="first_name"
                           value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}" autofocus=""
                           autocapitalize="none"
                           autocomplete="first_name" maxlength="254" required="" id="id_first_name"
                           class="form-control">

                    <label for="id_last_name" class="form-label">last_name:</label>
                    {% if form.last_name.errors %}
                        <div class="alert alert-danger alert-dismissible pb-0" role="alert" style="top:50px;">
                            <div class="form-error-1 text-center">{{ form.last_name.errors }}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                    <input type="text" name="last_name"
                           value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" autofocus=""
                           autocapitalize="none"
                           autocomplete="last_name" maxlength="254" required="" id="id_last_name" class="form-control">

                    <label for="id_password" class="form-label">password:</label>
                    {% if form.password.errors %}
                        <div class="alert alert-danger alert-dismissible pb-0" role="alert" style="top:50px;">
                            <div class="form-error-1 text-center">{{ form.password.errors }}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                    <input type="password" name="password"
                           value="{% if form.password.value %}{{ form.password.value }}{% endif %}" autofocus=""
                           autocapitalize="none"
                           autocomplete="password" maxlength="254" required="" id="id_password" class="form-control">

                    <label for="id_password_confirm" class="form-label">password_confirm:</label>
                    {% if form.password_confirm.errors %}
                        <div class="alert alert-danger alert-dismissible pb-0" role="alert" style="top:50px;">
                            <div class="form-error-1 text-center">{{ form.password_confirm.errors }}</div>
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endif %}
                    <input type="password" name="password_confirm"
                           value="{% if form.password_confirm.value %}{{ form.password_confirm.value }}{% endif %}"
                           autofocus=""
                           autocapitalize="none"
                           autocomplete="password_confirm" maxlength="254" required="" id="id_password_confirm"
                           class="form-control">


                    <div class="d-flex justify-content-between">
                        <button type="submit" class="custom-btn btn-1">Регістрація</button>

                    </div>
                </form>

                <a href="{% provider_login_url 'google' %}" class="btn">Увійти з
                    Google</a>

            </div>
        </div>
    </div>

{% endblock content %}

service/clients/templates/clients/register_jwt.html
{% extends 'base.html' %}

{% load static %}

{% block content %}
<div class="container" id="reg_container">
    <div class="d-flex justify-content-center my-3">
        <div class="col-md-6">
            <form id="registerForm" action="/auth/users/" method="post" content="application/json">
                <h2 class="text-center">{{ title }}</h2>
                {% csrf_token %}

                <div class="mb-3">
                    <label for="id_email" class="form-label">Email</label>
                    <div id="email-error-container" class="alert alert-danger d-none" role="alert">
                        <div id="email-error-message" class="form-error-1 text-center"></div>
                    </div>
                    <input type="email" class="form-control" name="email"
                           value="{% if form.email.value %}{{ form.email.value }}{% endif %}" id="id_email"
                           placeholder="Введіть вашу пошту" required>
                </div>

                <div class="mb-3">
                    <label for="id_first_name" class="form-label">Ім'я</label>
                    <div id="first_name-error-container" class="alert alert-danger d-none" role="alert">
                        <div id="first_name-error-message" class="form-error-1 text-center"></div>
                    </div>
                    <input type="text" class="form-control" name="first_name"
                           value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                           id="id_first_name" placeholder="Введіть ваше ім'я">
                </div>

                <div class="mb-3">
                    <label for="id_last_name" class="form-label">Прізвище</label>
                    <div id="last_name-error-container" class="alert alert-danger d-none" role="alert">
                        <div id="last_name-error-message" class="form-error-1 text-center"></div>
                    </div>
                    <input type="text" class="form-control" name="last_name"
                           value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}" id="id_last_name"
                           placeholder="Введіть ваше прізвище">
                </div>

                <div class="mb-3">
                    <label for="id_password" class="form-label">Введіть пароль</label>
                    <div id="password-error-container" class="alert alert-danger d-none" role="alert">
                        <div id="password-error-message" class="form-error-1 text-center"></div>
                    </div>
                    <input type="password" class="form-control" name="password" id="id_password"
                           placeholder="Введіть пароль" required>
                </div>

                <div class="d-flex justify-content-between">
                    <button type="submit" class="custom-btn btn-1">Регістрація</button>
                    <button class="gsi-material-button">
                        <div class="gsi-material-button-state"></div>
                        <div class="gsi-material-button-content-wrapper">
                            <div class="gsi-material-button-icon">
                                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"
                                     xmlns:xlink="http://www.w3.org/1999/xlink" style="display: block;">
                                    <path fill="#EA4335"
                                          d="M24 9.5c3.54 0 6.71 1.22 9.21 3.6l6.85-6.85C35.9 2.38 30.47 0 24 0 14.62 0 6.51 5.38 2.56 13.22l7.98 6.19C12.43 13.72 17.74 9.5 24 9.5z"></path>
                                    <path fill="#4285F4"
                                          d="M46.98 24.55c0-1.57-.15-3.09-.38-4.55H24v9.02h12.94c-.58 2.96-2.26 5.48-4.78 7.18l7.73 6c4.51-4.18 7.09-10.36 7.09-17.65z"></path>
                                    <path fill="#FBBC05"
                                          d="M10.53 28.59c-.48-1.45-.76-2.99-.76-4.59s.27-3.14.76-4.59l-7.98-6.19C.92 16.46 0 20.12 0 24c0 3.88.92 7.54 2.56 10.78l7.97-6.19z"></path>
                                    <path fill="#34A853"
                                          d="M24 48c6.48 0 11.93-2.13 15.89-5.81l-7.73-6c-2.15 1.45-4.92 2.3-8.16 2.3-6.26 0-11.57-4.22-13.47-9.91l-7.98 6.19C6.51 42.62 14.62 48 24 48z"></path>
                                    <path fill="none" d="M0 0h48v48H0z"></path>
                                </svg>
                            </div>
                        </div>
                    </button>
                </div>
            </form>

        </div>
    </div>
</div>
<div id="reg_success_message" class="container d-none" role="alert">
                <div id="reg_success_text" class="text-center" data-animation="fadeInLeft" data-delay="0.5s"></div>
            </div>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

<script>
$(document).ready(function () {
    $('#registerForm').on('submit', function (event) {
        event.preventDefault(); // Предотвращаем стандартное поведение формы
        var formData = $(this).serializeArray();
        var formObject = {};
        $.each(formData, function (index, field) {
            formObject[field.name] = field.value;
        });

        var jsonFormData = JSON.stringify(formObject);

        $.ajax({
            url: '/auth/users/', // URL для API регистрации
            type: 'POST',
            contentType: 'application/json', // Указываем формат данных
            data: jsonFormData,
            success: function () {
                $('#reg_container').empty();
                $('#reg_success_message').removeClass('d-none');
                $('#reg_success_text').html('Вам отправлено письмо для активации аккаунта на вашу почту.');
            },
            error: function (xhr) {
                var errors = xhr.responseJSON;
                console.log('Error:', errors);

                // Отображаем ошибки
                $('.alert').addClass('d-none'); // Скрываем все ошибки перед отображением новых
                $.each(errors, function (field, messages) {
                    var errorContainer = $('#' + field + '-error-container');
                    var errorMessage = $('#' + field + '-error-message');

                    if (messages) {
                        errorMessage.html(messages.join('<br>'));
                        errorContainer.removeClass('d-none');
                    } else {
                        errorContainer.addClass('d-none');
                    }
                });
            }
        });
    });
});
</script>
{% endblock content %}